function cleaned_file = cicada_matched_temporal_cleanup( ...
    orig_file, ...
    cleaned_template_file, ...
    task_dir, ...
    funcmask, ...
    output_dir, ...
    smoothing_kernel, ...
    fpass, ...
    detrend_degree, ...
    IC_selection_text)
% CICADA_MATCHED_TEMPORAL_CLEANUP
%
% Group CICADA matched temporal/ICA cleanup:
%
%       Yt = T(Y)
%       Mt = T(M)
%
% followed by the historical nonaggressive fsl_regfilt operation using
% the complete transformed MELODIC mixing matrix and the existing
% rejected-IC selection.
%
% BOLD voxel means are restored only AFTER fsl_regfilt.
%
% Spatial masking/smoothing is then handled by
% cicada_spatial_smooth_write.

%% Input files

melodic_mix_file = ...
    fullfile(task_dir, 'melodic', 'melodic_mix');

if ~isfile(orig_file)
    error('Original BOLD file does not exist: %s', orig_file);
end

if ~isfile(funcmask)
    error('Functional mask does not exist: %s', funcmask);
end

if ~isfile(melodic_mix_file)
    error('MELODIC mixing matrix does not exist: %s', ...
        melodic_mix_file);
end

if isempty(IC_selection_text)
    error('Rejected IC selection is empty.');
end


%% Read original BOLD

Y4 = niftiread(orig_file);
Yinfo = niftiinfo(orig_file);

funcmask_data = niftiread(funcmask);

if ~isequal( ...
        size(funcmask_data), ...
        size(Y4(:,:,:,1)))

    error('Functional mask dimensions do not match original BOLD.');

end

tr = Yinfo.PixelDimensions(4);

Y2 = reshape( ...
    Y4, ...
    [], ...
    size(Y4,4));


%% Preserve historical CICADA BOLD mean arithmetic

Ymeans = mean(Y2, 2);


%% Apply T to original BOLD

[Yt, ~, Y_temporal_info] = ...
    cicada_temporal_transform( ...
        Y2', ...
        tr, ...
        fpass, ...
        detrend_degree, ...
        Ymeans');

if ~all(isfinite(Yt(:)))
    error('T(Y) contains NaN or Inf.');
end


%% Apply identical T to complete MELODIC mixing matrix

M = readmatrix(melodic_mix_file);

if size(M,1) ~= size(Y4,4)
    error([ ...
        'melodic_mix time dimension (%d) does not match ', ...
        'BOLD time dimension (%d).'], ...
        size(M,1), ...
        size(Y4,4));
end

[Mt, ~, M_temporal_info] = ...
    cicada_temporal_transform( ...
        M, ...
        tr, ...
        fpass, ...
        detrend_degree);

if ~isequal(size(Mt), size(M))
    error('T(M) changed melodic_mix dimensions.');
end

if ~all(isfinite(Mt(:)))
    error('T(M) contains NaN or Inf.');
end


%% Temporary files required by fsl_regfilt

tmp_dir = tempname;
mkdir(tmp_dir);

cleanup_tmp = onCleanup(@() safe_remove_temp_dir(tmp_dir));

Yt_base = fullfile( ...
    tmp_dir, ...
    'matched_Yt.nii');

Yt_file = [Yt_base, '.gz'];

Mt_file = fullfile( ...
    tmp_dir, ...
    'matched_melodic_mix');

regfilt_base = fullfile( ...
    tmp_dir, ...
    'matched_regfilt.nii');

regfilt_file = [regfilt_base, '.gz'];


%% Write transformed BOLD

Yt4 = reshape( ...
    Yt', ...
    size(Y4,1), ...
    size(Y4,2), ...
    size(Y4,3), ...
    size(Y4,4));

Yt_info = Yinfo;
Yt_info.Datatype = 'single';

niftiwrite( ...
    cast(Yt4, 'single'), ...
    Yt_base, ...
    Yt_info, ...
    "Compressed", true);


%% Write transformed complete mixing matrix

fid = fopen(Mt_file, 'w');

if fid == -1
    error('Could not create transformed melodic_mix file.');
end

cleanup_fid = onCleanup(@() fclose(fid));

fmt = [ ...
    repmat('%.17g\t', 1, size(Mt,2)-1), ...
    '%.17g\n'];

for r = 1:size(Mt,1)
    fprintf(fid, fmt, Mt(r,:));
end

clear cleanup_fid


%% Same historical nonaggressive fsl_regfilt semantics

fsl_regfilt_command = [ ...
    'fsl_regfilt -i "', Yt_file, '"', ...
    ' -f "', IC_selection_text, '"', ...
    ' -d "', Mt_file, '"', ...
    ' -m "', funcmask, '"', ...
    ' -o "', regfilt_base, '"' ];

fprintf('Running matched Group CICADA ICA cleanup:\n%s\n', ...
    fsl_regfilt_command);

[status, command_output] = ...
    call_fsl(fsl_regfilt_command);

if status ~= 0
    error( ...
        'Matched fsl_regfilt failed:\n%s', ...
        command_output);
end

if ~isfile(regfilt_file)
    error('Matched fsl_regfilt output was not created.');
end


%% Restore original BOLD voxel means AFTER regression

matched_zero_mean = ...
    niftiread(regfilt_file);

if ~isequal(size(matched_zero_mean), size(Y4))
    error('Matched fsl_regfilt output dimensions are incorrect.');
end

matched2 = reshape( ...
    matched_zero_mean, ...
    [], ...
    size(matched_zero_mean,4));

matched2 = matched2 + Ymeans;

matched4 = reshape( ...
    matched2, ...
    size(matched_zero_mean));


%% Spatial smoothing geometry

voxel_sizes_mm = ...
    Yinfo.PixelDimensions(1:3);

[sigma_vox, sigma_mm, voxel_sizes_mm] = ...
    cicada_fwhm_mm_to_sigma_vox( ...
        smoothing_kernel, ...
        voxel_sizes_mm);

fprintf([ ...
    '  Output smoothing geometry: requested FWHM = %.12g mm; ', ...
    'voxel sizes = [%.12g %.12g %.12g] mm; sigma = ', ...
    '%.12g mm = [%.12g %.12g %.12g] voxels.\n'], ...
    smoothing_kernel, ...
    voxel_sizes_mm, ...
    sigma_mm, ...
    sigma_vox);


%% Preserve canonical cleaned-file naming

[~, file_name, ~] = ...
    fileparts(cleaned_template_file);


%% Shared spatial preparation / writing

cleaned_file = ...
    cicada_spatial_smooth_write( ...
        matched4, ...
        funcmask_data, ...
        Yinfo, ...
        file_name, ...
        output_dir, ...
        smoothing_kernel, ...
        sigma_vox, ...
        Y_temporal_info.filtered, ...
        Y_temporal_info.detrended);

end


function safe_remove_temp_dir(tmp_dir)

if isfolder(tmp_dir)
    rmdir(tmp_dir, 's');
end

end