function cleaned_file = cicada_spatial_smooth_write( ...
    filtered_signal, ...
    funcmask_data, ...
    file_orig_data_info, ...
    file_name, ...
    output_dir, ...
    smoothing_kernel, ...
    sigma_vox, ...
    bp, ...
    detrended)
% CICADA_SPATIAL_SMOOTH_WRITE
%
% Apply functional-mask handling and optional
% mask-normalized Gaussian output smoothing, then write the prepared
% Group CICADA file.
%
% This helper contains no temporal processing.
%
% Inputs
%   filtered_signal      [X Y Z T] temporally prepared BOLD
%   funcmask_data        3-D functional mask
%   file_orig_data_info  NIfTI header/provenance source
%   file_name            base name used by historical CICADA naming
%   output_dir           destination directory
%   smoothing_kernel     requested FWHM in mm
%   sigma_vox            per-axis Gaussian sigma in voxels
%   bp                   whether temporal filtering was applied
%   detrended            whether detrending was applied

if ~isequal(size(funcmask_data), size(filtered_signal(:,:,:,1)))
    error('Funcmask size does not match Data size.');
end

%% Mask temporally prepared data

file_filtered_data = zeros(size(filtered_signal));

for idx2 = 1:size(filtered_signal,4)
    curr_file_data = filtered_signal(:,:,:,idx2);
    curr_file_data(funcmask_data == 0) = 0;
    file_filtered_data(:,:,:,idx2) = curr_file_data;
end


%% Optional spatial smoothing

if smoothing_kernel ~= 0

    fprintf('  Smoothing at %g mm FWHM...\n', smoothing_kernel)

    file_data = zeros(size(filtered_signal));

    smoothing_tag = ...
        cicada_smoothing_fwhm_tag(smoothing_kernel);

    mask_bin = double(funcmask_data ~= 0);

    mask_smooth = imgaussfilt3( ...
        mask_bin, ...
        sigma_vox);

    for idx2 = 1:size(filtered_signal,4)

        curr_smoothed = imgaussfilt3( ...
            file_filtered_data(:,:,:,idx2), ...
            sigma_vox);

        curr_file_data = zeros( ...
            size(curr_smoothed), ...
            'like', ...
            curr_smoothed);

        valid = ...
            (mask_bin ~= 0) & ...
            (mask_smooth > 0);

        curr_file_data(valid) = ...
            curr_smoothed(valid) ./ ...
            mask_smooth(valid);

        file_data(:,:,:,idx2) = ...
            curr_file_data;

    end


    if bp == 1

        if detrended == 1

            niftiwrite( ...
                cast(file_data, 'single'), ...
                [output_dir, '/', smoothing_tag, ...
                 '_bp_d_', file_name], ...
                file_orig_data_info, ...
                "Compressed", true);

            cleaned_file = ...
                [output_dir, '/', smoothing_tag, ...
                 '_bp_d_', file_name, '.gz'];

        else

            niftiwrite( ...
                cast(file_data, 'single'), ...
                [output_dir, '/', smoothing_tag, ...
                 '_bp_', file_name], ...
                file_orig_data_info, ...
                "Compressed", true);

            cleaned_file = ...
                [output_dir, '/', smoothing_tag, ...
                 '_bp_', file_name, '.gz'];

        end

    else

        if detrended == 1

            niftiwrite( ...
                cast(file_data, 'single'), ...
                [output_dir, '/', smoothing_tag, ...
                 '_d_', file_name], ...
                file_orig_data_info, ...
                "Compressed", true);

            cleaned_file = ...
                [output_dir, '/', smoothing_tag, ...
                 '_d_', file_name, '.gz'];

        else

            niftiwrite( ...
                cast(file_data, 'single'), ...
                [output_dir, '/', smoothing_tag, ...
                 '_', file_name], ...
                file_orig_data_info, ...
                "Compressed", true);

            cleaned_file = ...
                [output_dir, '/', smoothing_tag, ...
                 '_', file_name, '.gz'];

        end

    end


else

    fprintf('   Not Smoothing! \n')

    file_data = file_filtered_data;

    if bp == 1

        if detrended == 1

            niftiwrite( ...
                cast(file_data, 'single'), ...
                [output_dir, '/bp_d_', file_name], ...
                file_orig_data_info, ...
                "Compressed", true);

            cleaned_file = ...
                [output_dir, '/bp_d_', file_name, '.gz'];

        else

            niftiwrite( ...
                cast(file_data, 'single'), ...
                [output_dir, '/bp_', file_name], ...
                file_orig_data_info, ...
                "Compressed", true);

            cleaned_file = ...
                [output_dir, '/bp_', file_name, '.gz'];

        end

    else

        if detrended == 1

            niftiwrite( ...
                cast(file_data, 'single'), ...
                [output_dir, '/d_', file_name], ...
                file_orig_data_info, ...
                "Compressed", true);

            cleaned_file = ...
                [output_dir, '/d_', file_name, '.gz'];

        else

            niftiwrite( ...
                cast(file_data, 'single'), ...
                [output_dir, '/', file_name], ...
                file_orig_data_info, ...
                "Compressed", true);

            cleaned_file = ...
                [output_dir, '/', file_name, '.gz'];

        end

    end

end

end